// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turbo.Database.Context;

#nullable disable

namespace Turbo.Main.Migrations
{
    [DbContext(typeof(TurboContext))]
    [Migration("20240922120422_UpdateNavigatorEntities")]
    partial class UpdateNavigatorEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Turbo.Core.Database.Entities.Catalog.CatalogOfferEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("CanBundle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_bundle")
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("CanGift")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_gift")
                        .HasDefaultValueSql("1");

                    b.Property<int>("CatalogPageEntityId")
                        .HasColumnType("int")
                        .HasColumnName("page_id");

                    b.Property<int>("ClubLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("club_level")
                        .HasDefaultValueSql("0");

                    b.Property<int>("CostCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cost_credits")
                        .HasDefaultValueSql("0");

                    b.Property<int>("CostCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cost_currency")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrencyType")
                        .HasColumnType("int")
                        .HasColumnName("currency_type");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LocalizationId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("localization_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("Visible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visible")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("CatalogPageEntityId");

                    b.ToTable("catalog_offers");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Catalog.CatalogPageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Icon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("icon")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ImageData")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("image_data");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("layout")
                        .HasDefaultValueSql("'default_3x3'");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("localization");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentEntityId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("TextData")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("text_data");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("Visible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visible")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("ParentEntityId");

                    b.ToTable("catalog_pages");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Catalog.CatalogProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CatalogOfferEntityId")
                        .HasColumnType("int")
                        .HasColumnName("offer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExtraParam")
                        .HasColumnType("longtext")
                        .HasColumnName("extra_param");

                    b.Property<int?>("FurnitureDefinitionEntityId")
                        .HasColumnType("int")
                        .HasColumnName("definition_id");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_type");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quantity")
                        .HasDefaultValueSql("1");

                    b.Property<int>("UniqueRemaining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("unique_remaining")
                        .HasDefaultValueSql("0");

                    b.Property<int>("UniqueSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("unique_size")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CatalogOfferEntityId");

                    b.HasIndex("FurnitureDefinitionEntityId");

                    b.ToTable("catalog_products");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Furniture.FurnitureDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("CanGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_group")
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("CanLay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_lay")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("CanRecycle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_recycle")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("CanSell")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_sell")
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("CanSit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_sit")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("CanStack")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_stack")
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("CanTrade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_trade")
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("CanWalk")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_walk")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExtraData")
                        .HasColumnType("longtext")
                        .HasColumnName("extra_data");

                    b.Property<string>("Logic")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("logic")
                        .HasDefaultValueSql("'default'");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<string>("PublicName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("public_name");

                    b.Property<int>("SpriteId")
                        .HasColumnType("int")
                        .HasColumnName("sprite_id");

                    b.Property<int>("TotalStates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_states")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'s'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsagePolicy")
                        .HasColumnType("int")
                        .HasColumnName("usage_policy")
                        .HasDefaultValueSql("1");

                    b.Property<int>("X")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("x")
                        .HasDefaultValueSql("0");

                    b.Property<int>("Y")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("y")
                        .HasDefaultValueSql("1");

                    b.Property<double>("Z")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double(10,3)")
                        .HasColumnName("z")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.HasIndex("SpriteId", "Type")
                        .IsUnique();

                    b.ToTable("furniture_definitions");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Furniture.FurnitureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FurnitureDefinitionEntityId")
                        .HasColumnType("int")
                        .HasColumnName("definition_id");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int?>("RoomEntityId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int>("Rotation")
                        .HasColumnType("int")
                        .HasColumnName("direction")
                        .HasDefaultValueSql("0");

                    b.Property<string>("StuffData")
                        .HasColumnType("longtext")
                        .HasColumnName("stuff_data");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("WallPosition")
                        .HasColumnType("longtext")
                        .HasColumnName("wall_position");

                    b.Property<int>("X")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("x")
                        .HasDefaultValueSql("0");

                    b.Property<int>("Y")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("y")
                        .HasDefaultValueSql("0");

                    b.Property<double>("Z")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double(10,3)")
                        .HasColumnName("z")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureDefinitionEntityId");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("RoomEntityId");

                    b.ToTable("furniture");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Furniture.FurnitureTeleportLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FurnitureEntityOneId")
                        .HasColumnType("int")
                        .HasColumnName("furniture_one_id");

                    b.Property<int>("FurnitureEntityTwoId")
                        .HasColumnType("int")
                        .HasColumnName("furniture_two_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureEntityOneId")
                        .IsUnique();

                    b.HasIndex("FurnitureEntityTwoId")
                        .IsUnique();

                    b.ToTable("furniture_teleport_links");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Messenger.MessengerCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId", "Name")
                        .IsUnique();

                    b.ToTable("messenger_categories");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Messenger.MessengerFriendEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FriendPlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("requested_id");

                    b.Property<int?>("MessengerCategoryEntityId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("RelationType")
                        .HasColumnType("int")
                        .HasColumnName("relation");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FriendPlayerEntityId");

                    b.HasIndex("MessengerCategoryEntityId");

                    b.HasIndex("PlayerEntityId", "FriendPlayerEntityId")
                        .IsUnique();

                    b.ToTable("messenger_friends");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Messenger.MessengerRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("RequestedPlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("requested_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RequestedPlayerEntityId");

                    b.HasIndex("PlayerEntityId", "RequestedPlayerEntityId")
                        .IsUnique();

                    b.ToTable("messenger_requests");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Navigator.NavigatorEventCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("navigator_eventcats");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Navigator.NavigatorFlatCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Automatic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("automatic");

                    b.Property<string>("AutomaticCategory")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("automatic_category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GlobalCategory")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("global_category");

                    b.Property<int>("MinRank")
                        .HasColumnType("int")
                        .HasColumnName("min_rank");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int")
                        .HasColumnName("order_num");

                    b.Property<bool>("StaffOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("staff_only");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("navigator_flatcats");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Navigator.NavigatorTopLevelContextEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int")
                        .HasColumnName("order_num");

                    b.Property<string>("SearchCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("search_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.HasIndex("SearchCode")
                        .IsUnique();

                    b.ToTable("navigator_top_level_contexts");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerBadgeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BadgeCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("badge_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("slot_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId", "BadgeCode")
                        .IsUnique();

                    b.ToTable("player_badges");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerChatStyleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClientStyleId")
                        .HasColumnType("int")
                        .HasColumnName("client_style_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientStyleId")
                        .IsUnique();

                    b.ToTable("player_chat_styles");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerChatStyleOwnedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ChatStyleId")
                        .HasColumnType("int")
                        .HasColumnName("chat_style_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChatStyleId");

                    b.HasIndex("PlayerEntityId", "ChatStyleId")
                        .IsUnique();

                    b.ToTable("player_chat_styles_owned");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerCurrencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("amount")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId", "Type")
                        .IsUnique();

                    b.ToTable("player_currencies");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Figure")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("figure")
                        .HasDefaultValueSql("'hr-115-42.hd-195-19.ch-3030-82.lg-275-1408.fa-1201.ca-1804-64'");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Motto")
                        .HasColumnType("longtext")
                        .HasColumnName("motto");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("PlayerStatus")
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("RoomChatStyleId")
                        .HasColumnType("int")
                        .HasColumnName("room_chat_style_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("players");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomBanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateExpires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_expires");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("RoomEntityId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("RoomEntityId", "PlayerEntityId")
                        .IsUnique();

                    b.ToTable("room_bans");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomChatlogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("message");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("RoomEntityId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int?>("TargetPlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("target_player_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("RoomEntityId");

                    b.HasIndex("TargetPlayerEntityId");

                    b.ToTable("room_chatlogs");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("AllowEditing")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_editing")
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("AllowPets")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_pets")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("AllowPetsEat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_pets_eat")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("AllowWalkThrough")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_walk_through")
                        .HasDefaultValueSql("1");

                    b.Property<int>("BanType")
                        .HasColumnType("int")
                        .HasColumnName("ban_type")
                        .HasDefaultValueSql("0");

                    b.Property<int>("ChatDistance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chat_distance")
                        .HasDefaultValueSql("50");

                    b.Property<int>("ChatModeType")
                        .HasColumnType("int")
                        .HasColumnName("chat_mode_type")
                        .HasDefaultValueSql("0");

                    b.Property<int>("ChatProtectionType")
                        .HasColumnType("int")
                        .HasColumnName("chat_protection_type")
                        .HasDefaultValueSql("2");

                    b.Property<int>("ChatSpeedType")
                        .HasColumnType("int")
                        .HasColumnName("chat_speed_type")
                        .HasDefaultValueSql("1");

                    b.Property<int>("ChatWeightType")
                        .HasColumnType("int")
                        .HasColumnName("chat_weight_type")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool?>("HideWalls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("hide_walls")
                        .HasDefaultValueSql("0");

                    b.Property<int>("KickType")
                        .HasColumnType("int")
                        .HasColumnName("kick_type")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("LastActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_active");

                    b.Property<int>("MuteType")
                        .HasColumnType("int")
                        .HasColumnName("mute_type")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("NavigatorCategoryEntityId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<double>("PaintFloor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasColumnName("paint_floor")
                        .HasDefaultValueSql("0");

                    b.Property<double>("PaintLandscape")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasColumnName("paint_landscape")
                        .HasDefaultValueSql("0");

                    b.Property<double>("PaintWall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasColumnName("paint_wall")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("RoomModelEntityId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<int>("RoomState")
                        .HasColumnType("int")
                        .HasColumnName("state")
                        .HasDefaultValueSql("0");

                    b.Property<int>("ThicknessFloor")
                        .HasColumnType("int")
                        .HasColumnName("thickness_floor")
                        .HasDefaultValueSql("0");

                    b.Property<int>("ThicknessWall")
                        .HasColumnType("int")
                        .HasColumnName("thickness_wall")
                        .HasDefaultValueSql("0");

                    b.Property<int>("TradeType")
                        .HasColumnType("int")
                        .HasColumnName("trade_type")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsersMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("users_max")
                        .HasDefaultValueSql("25");

                    b.Property<int>("UsersNow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("users_now")
                        .HasDefaultValueSql("0");

                    b.Property<int>("WallHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wall_height")
                        .HasDefaultValueSql("-1");

                    b.HasKey("Id");

                    b.HasIndex("NavigatorCategoryEntityId");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("RoomModelEntityId");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("Custom")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("custom")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DoorRotation")
                        .HasColumnType("int")
                        .HasColumnName("door_rotation")
                        .HasDefaultValueSql("0");

                    b.Property<int>("DoorX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("door_x")
                        .HasDefaultValueSql("0");

                    b.Property<int>("DoorY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("door_y")
                        .HasDefaultValueSql("0");

                    b.Property<bool?>("Enabled")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("room_models");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomMuteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateExpires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_expires");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("RoomEntityId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("RoomEntityId", "PlayerEntityId")
                        .IsUnique();

                    b.ToTable("room_mutes");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomRightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("RoomEntityId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("RoomEntityId", "PlayerEntityId")
                        .IsUnique();

                    b.ToTable("room_rights");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Security.SecurityTicketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_locked")
                        .HasDefaultValueSql("0");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId")
                        .IsUnique();

                    b.HasIndex("Ticket")
                        .IsUnique();

                    b.ToTable("security_tickets");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Tracking.PerformanceLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AverageFrameRate")
                        .HasColumnType("int")
                        .HasColumnName("average_frame_rate");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("browser");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("int")
                        .HasColumnName("elapsed_time");

                    b.Property<string>("FlashVersion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("flash_version");

                    b.Property<int>("GarbageCollections")
                        .HasColumnType("int")
                        .HasColumnName("garbage_collections");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDebugger")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_debugger");

                    b.Property<int>("MemoryUsage")
                        .HasColumnType("int")
                        .HasColumnName("memory_usage");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("os");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("ElapsedTime");

                    b.HasIndex("IPAddress");

                    b.ToTable("performance_logs");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Catalog.CatalogOfferEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Catalog.CatalogPageEntity", "Page")
                        .WithMany("Offers")
                        .HasForeignKey("CatalogPageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Catalog.CatalogPageEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Catalog.CatalogPageEntity", "ParentEntity")
                        .WithMany("Children")
                        .HasForeignKey("ParentEntityId");

                    b.Navigation("ParentEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Catalog.CatalogProductEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Catalog.CatalogOfferEntity", "Offer")
                        .WithMany("Products")
                        .HasForeignKey("CatalogOfferEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Furniture.FurnitureDefinitionEntity", "FurnitureDefinition")
                        .WithMany()
                        .HasForeignKey("FurnitureDefinitionEntityId");

                    b.Navigation("FurnitureDefinition");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Furniture.FurnitureEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Furniture.FurnitureDefinitionEntity", "FurnitureDefinitionEntity")
                        .WithMany("Furnitures")
                        .HasForeignKey("FurnitureDefinitionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("Furniture")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Room.RoomEntity", "RoomEntity")
                        .WithMany()
                        .HasForeignKey("RoomEntityId");

                    b.Navigation("FurnitureDefinitionEntity");

                    b.Navigation("PlayerEntity");

                    b.Navigation("RoomEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Furniture.FurnitureTeleportLinkEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Furniture.FurnitureEntity", "FurnitureEntityOne")
                        .WithMany()
                        .HasForeignKey("FurnitureEntityOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Furniture.FurnitureEntity", "FurnitureEntityTwo")
                        .WithMany()
                        .HasForeignKey("FurnitureEntityTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FurnitureEntityOne");

                    b.Navigation("FurnitureEntityTwo");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Messenger.MessengerCategoryEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("MessengerCategories")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Messenger.MessengerFriendEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "FriendPlayerEntity")
                        .WithMany()
                        .HasForeignKey("FriendPlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Messenger.MessengerCategoryEntity", "MessengerCategoryEntity")
                        .WithMany()
                        .HasForeignKey("MessengerCategoryEntityId");

                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("MessengerFriends")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FriendPlayerEntity");

                    b.Navigation("MessengerCategoryEntity");

                    b.Navigation("PlayerEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Messenger.MessengerRequestEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("MessengerRequestsSent")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "RequestedPlayerEntity")
                        .WithMany("MessengerRequests")
                        .HasForeignKey("RequestedPlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");

                    b.Navigation("RequestedPlayerEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerBadgeEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("PlayerBadges")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerChatStyleOwnedEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerChatStyleEntity", "ChatStyle")
                        .WithMany("OwnedChatStyles")
                        .HasForeignKey("ChatStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("PlayerOwnedChatStyles")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatStyle");

                    b.Navigation("PlayerEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerCurrencyEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("PlayerCurrencies")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomBanEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("RoomBans")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Room.RoomEntity", "RoomEntity")
                        .WithMany("RoomBans")
                        .HasForeignKey("RoomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");

                    b.Navigation("RoomEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomChatlogEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("RoomChatlogs")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Room.RoomEntity", "RoomEntity")
                        .WithMany("RoomChats")
                        .HasForeignKey("RoomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "TargetPlayerEntity")
                        .WithMany()
                        .HasForeignKey("TargetPlayerEntityId");

                    b.Navigation("PlayerEntity");

                    b.Navigation("RoomEntity");

                    b.Navigation("TargetPlayerEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Navigator.NavigatorFlatCategoryEntity", "NavigatorFlatCategoryEntity")
                        .WithMany()
                        .HasForeignKey("NavigatorCategoryEntityId");

                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("Rooms")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Room.RoomModelEntity", "RoomModelEntity")
                        .WithMany()
                        .HasForeignKey("RoomModelEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NavigatorFlatCategoryEntity");

                    b.Navigation("PlayerEntity");

                    b.Navigation("RoomModelEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomMuteEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("RoomMutes")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Room.RoomEntity", "RoomEntity")
                        .WithMany("RoomMutes")
                        .HasForeignKey("RoomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");

                    b.Navigation("RoomEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomRightEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("RoomRights")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turbo.Core.Database.Entities.Room.RoomEntity", "RoomEntity")
                        .WithMany("RoomRights")
                        .HasForeignKey("RoomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");

                    b.Navigation("RoomEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Security.SecurityTicketEntity", b =>
                {
                    b.HasOne("Turbo.Core.Database.Entities.Players.PlayerEntity", "PlayerEntity")
                        .WithMany("SecurityTickets")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Catalog.CatalogOfferEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Catalog.CatalogPageEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Furniture.FurnitureDefinitionEntity", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerChatStyleEntity", b =>
                {
                    b.Navigation("OwnedChatStyles");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Players.PlayerEntity", b =>
                {
                    b.Navigation("Furniture");

                    b.Navigation("MessengerCategories");

                    b.Navigation("MessengerFriends");

                    b.Navigation("MessengerRequests");

                    b.Navigation("MessengerRequestsSent");

                    b.Navigation("PlayerBadges");

                    b.Navigation("PlayerCurrencies");

                    b.Navigation("PlayerOwnedChatStyles");

                    b.Navigation("RoomBans");

                    b.Navigation("RoomChatlogs");

                    b.Navigation("RoomMutes");

                    b.Navigation("RoomRights");

                    b.Navigation("Rooms");

                    b.Navigation("SecurityTickets");
                });

            modelBuilder.Entity("Turbo.Core.Database.Entities.Room.RoomEntity", b =>
                {
                    b.Navigation("RoomBans");

                    b.Navigation("RoomChats");

                    b.Navigation("RoomMutes");

                    b.Navigation("RoomRights");
                });
#pragma warning restore 612, 618
        }
    }
}
